development:
  adapter: postgresql
  encoding: unicode
  database: nochat_development

test:
  adapter: postgresql
  encoding: unicode
  database: nochat_test

production:
  adapter: postgresql
  encoding: unicode
  database: nochat_production

